name: screws
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - expat=2.5.0
  - gdcm=2.8.9
  - json-c=0.17
  - lerc=4.0.0
  - libcxx=16.0.6
  - libdeflate=1.20
  - libexpat=2.5.0
  - libffi=3.4.4
  - libjpeg-turbo=3.0.0
  - libpng=1.6.43
  - libsqlite=3.45.2
  - libtiff=4.6.0
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - ncurses=6.4
  - openjpeg=2.5.2
  - openssl=3.2.1
  - pip=23.3.1
  - python=3.12.2
  - python_abi=3.12
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.13
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - annotated-types==0.6.0
      - appnope==0.1.4
      - arrow==1.3.0
      - asttokens==2.4.1
      - cachetools==5.3.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - executing==2.0.1
      - fonttools==4.50.0
      - fqdn==1.5.1
      - google-api-core==2.18.0
      - google-auth==2.29.0
      - googleapis-common-protos==1.63.0
      - idna==3.6
      - ipykernel==6.29.4
      - ipython==8.23.0
      - isoduration==20.11.0
      - jedi==0.19.1
      - jsonpointer==2.4
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - kiwisolver==1.4.5
      - labelbox==3.66.0
      - matplotlib==3.8.3
      - matplotlib-inline==0.1.6
      - nest-asyncio==1.6.0
      - numpy==1.26.4
      - opencv-python==4.9.0.80
      - packaging==24.0
      - parso==0.8.3
      - pexpect==4.9.0
      - pillow==10.3.0
      - pip-autoremove==0.10.0
      - platformdirs==4.2.0
      - prompt-toolkit==3.0.43
      - proto-plus==1.23.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pydicom==2.4.4
      - pygments==2.17.2
      - pyparsing==3.1.2
      - python-dateutil==2.8.2
      - pyzmq==25.1.2
      - requests==2.31.0
      - rsa==4.9
      - six==1.16.0
      - stack-data==0.6.3
      - strenum==0.4.15
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.2
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.11.0
      - uri-template==1.3.0
      - urllib3==2.2.1
      - wcwidth==0.2.13
      - webcolors==1.13
